#!/bin/bash

# FED team ID
TEAM_ID=2005108

if [[ "$ACCESS_TOKEN" == "" && -f ~/.github_token ]]; then
    ACCESS_TOKEN=`cat ~/.github_token`
fi

if [[ "$ACCESS_TOKEN" == "" ]]; then
    echo "Please set env variable ACCESS_TOKEN to a Github access token or store it in ~/.github_token; go to https://github.com/settings/tokens to create one."
    exit 1;
fi

fix_usecase(){
	grep -q "^usecase:" metadata.yaml && sed -i '' "s/.*usecase.*/usecase: \"$REPO\"/" metadata.yaml || 
	printf "\nusecase: \"$REPO\"" >> metadata.yaml
}

fix_repo_url(){
	grep -q "^repository_url:" metadata.yaml
	if [ $? -eq 0 ]
	then	
		sed -i '' "s;.*repository_url.*;repository_url: \"https://github.com/Scout24/$REPO\";" metadata.yaml
	else 
		printf "\nrepository_url: \"https://github.com/Scout24/$REPO\"" >> metadata.yaml
	fi
}

add_timeout_to_jenkinsfile(){
	grep -q "Continue?" Jenkinsfile
	if [ $? -eq 0 ]
	then	
		sed -i '' "s;.*Continue?.*;        timeout(time: 1, unit: 'HOURS') { input 'Continue?' };" Jenkinsfile
	fi
}

# filter out repos our team is not admin of; otherwise, e.g. security-configuration would appear in the list as of now (2017-12)
REPO_NAME_FILTER="map(select(.permissions.admin == true)) | map(.name) | .[]"

REPO_NAMES=`http GET "https://api.github.com/teams/$TEAM_ID/repos?per_page=100&access_token=$ACCESS_TOKEN" | jq -r "$REPO_NAME_FILTER" | sort`

for REPO in $REPO_NAMES; do
	echo $REPO
	cd ~/git/$REPO

	if [ -f Jenkinsfile ]; then

			git stash
			git checkout master
			git pull

			add_timeout_to_jenkinsfile

			git diff

			read -p "Should i commit and push changes? [y/n] " -n 1 -r
			echo

			if [[ $REPLY =~ ^[Yy]$ ]]
			then
				git commit -am "Add timeout for approval step"
				git push
			fi

	fi

    continue
done;


