#!/bin/bash
# emulates sort -V

[ "$1" = '-r' ] && flag="$1"
while read -r it; do
    <<<"$it" sed 's/\([0-9][0-9]*\)/0000000000\1/g;s/[0-9]*\([0-9]\{10\}\)/\1/g'
    echo "$it"
done |
paste - - | sort $flag -n -k 1 -t$'\t' | cut -f 2 -d$'\t'